version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - POSTGRES_DB=app
